# trivy_scan.yml

on:
  push:
    paths:
      - '**/*' # Trigger on any file change

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.16.1
            
